version: '2'
services:
    api:
        build: .
        ports:
            - "80:80"
        volumes:
            - "$PWD/for_devs/dev_mongo_config:/mongo"
        environment:
            - APP_DEBUG=True
    ui:
        build: web/web-app
        ports:
            - "3000:3000"
        environment:
            - REACT_APP_APP_SERVER=http://localhost
            - REACT_APP_APP_SERVER_PORT=80
        depends_on:
            - api
