apiVersion: v1
kind: Service
metadata:
    name: web-app-api
    namespace: web-app
    labels:
        run: web-app
        tier: web-app-api
spec:
    type: ClusterIP
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
        run: web-app
        tier: web-app-api
---
apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret
    namespace: web-app
type: Opaque
data:
    connection: # ADD YOUR BASE64 ENCODED CONNECTION STRING HERE
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-app-api
    namespace: web-app
spec:
    selector:
        matchLabels:
            run: web-app
            tier: web-app-api
    replicas: 1
    template:
        metadata:
            labels:
                run: web-app
                tier: web-app-api
        spec:
            containers: 
            - name: web-app-api
              image: gcr.io/web-server-app-demo/web_app_api:0.1
              imagePullPolicy: Always
              readinessProbe:
                  httpGet:
                      path: /api/v1/status/
                      port: 80
              livenessProbe:
                  httpGet:
                      path: /api/v1/status/
                      port: 80
              env:
                  - name: APP_DEBUG
                    value: "True"
              ports:
              - containerPort: 80
              volumeMounts:
              - name: mongo
                mountPath: "mongo"
                readOnly: true
            volumes:
            - name: mongo
              secret:
                  secretName: mongo-secret
